### ISSUE TITLE
Mismatch in FDI expression

### ISSUE THREAD

**Issue by EmanuelCastanho** [marine-debris/marine-debris.github.io#3]
Hi, why MARIDA algorithm uses l_redge instead of l_red proposed by Biermann et al. 2020 to calculate FDI?

r_acc = band6 + 10*(band10 - band6)*(l_nir - l_redge)/(l_swir - l_redge)

**Comment by gkakogeorgiou** [comment]
Hi Emanuel,
 
The definition of FDI is similar to that of FAI (Hu, 2009) and MCI (Gower et al., 2005). So theoretically, the l_redge is the most appropriate since the baseline reflectance is derived from linear interpolation between the red edge band (not the red band) and the swir band. We estimated FDI in MARIDA dataset with both l_red and l_regde, and we found that although there are some slight differences in values, FDI functionality does not change at all. Keep in mind that FDI alone is not able to discriminate marine debris from other floating materials. This has been shown in both studies of Kikaki et al. (2022) and Biermann et al. (2020).  

Let me know if you have any questions,
Yannis
