### ISSUE TITLE
Link for dataset_si and dataset_glcm is broken

### ISSUE THREAD

**Issue by Zhanarik** [marine-debris/marine-debris.github.io#6]
Hello everyone, 

The link for the dataset_si.h5 and dataset_glcm.h5 is broken :((( 

Could someone please fix the link?) 
I was trying to run on my own pc, but the progress bar stops moving at a point. 

I would be very thankfull if someone can share these files with me. 

The indices/ and texture/ folders as well as the dataset_si.h5 and dataset_glcm.h5 files from [here](https://pithos.okeanos.grnet.gr/public/7Xm6x2uSBHTknNv7vaqgS6).
<img width="665" alt="Screen Shot 2023-02-17 at 12 18 51" src="https://user-images.githubusercontent.com/43060102/219564631-98020297-5ce8-4bdb-a44a-4b4990c4d3da.png">

**Comment by EmanuelCastanho** [comment]
Hi @Zhanarik , you can download the original MARIDA from here: https://zenodo.org/record/5151941#.Y-9XDi-ZNzU
I was only able to run `python engineering_patches.py --type texture` when I created a new environment with the most recent Python version and installed only the packages that the script `engineering_patches.py` was asking for. Just install the packages until the script doesn't give errors anymore. Keep in mind that you will not be able to use this environment to run every script of MARIDA.

I processed these files some time ago, so if you are in a hurry you can use this link, I might delete this in the future since it uses a lot of personal storage: https://drive.google.com/file/d/11e3N2cz9SDY2YMLDNtfkSI0r15R_3FNO/view?usp=share_link

**Comment by Zhanarik** [comment]
@EmanuelCastanho Thank you very much for providing the link and sharing you experiences.
I do have the link and dataset that downloaded from https://zenodo.org/record/5151941#.Y-9XDi-ZNzU  

What I can't obtain by running the code is the file called dataset_glcm.h5 
I see that, you do not have this in your drive, but anyway thank youuuu :)

**Comment by EmanuelCastanho** [comment]
@Zhanarik I thought you were having problems creating the `dataset_glcm.h5` because you didn't have the texture folder that I shared.
Anyway, please check the drive again, I added the `dataset_glcm.h5` :)

**Comment by Zhanarik** [comment]
@EmanuelCastanho Thank you very much!!!!!!
I downloaded the file, thank you agaain!!! You saved me!! 
Have a nice weekend :)
